version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'maven'
    directory: '/java-wasm'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'bundler'
    directory: '/gemfiles/2.7'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'bundler'
    directory: '/gemfiles/3.0'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'bundler'
    directory: '/gemfiles/3.1'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'bundler'
    directory: '/gemfiles/3.2'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'bundler'
    directory: '/gemfiles/3.3'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'bundler'
    directory: '/gemfiles/3.4'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'bundler'
    directory: '/gemfiles/jruby'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'bundler'
    directory: '/gemfiles/truffleruby'
    schedule:
      interval: 'weekly'
